services:
  blog-app:
    image: laravel-blog:latest
    ports:
      - "8080:8080"
    container_name: blog-app
    environment:
      APP_ENV: production
      APP_DEBUG: false
      APP_URL: http://localhost
      REDIS_HOST: redis
    networks:
      - blog-network
    restart: always

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - blog-network
    restart: always

networks:
  blog-network:
    driver: bridge
